### PR TITLE
feat: upgrade to harlem v3

### PR DESCRIPTION
**Pull request by Lexpeartha**
PR to help move move onto the new Harlem version

### CODE REVIEW

**Comment by Lexpeartha** [comment]
Currently module crashes and `window is not defined` error is thrown. Tried experimenting by moving certain parts to `app:beforeMount` and `app:mounted` hooks, but didn't fix it. Feeling stuck atm, would really appreciate help

**Comment by danielroe** [comment]
Apologies for the lack of response! It's possible the issue is upstream in Harlem.

**Comment by Lexpeartha** [comment]
> Apologies for the lack of response! It's possible the issue is upstream in Harlem.

Hi, thanks for looking into this. Do you want me open an issue about this in the harlem repo then?

**Comment by Lexpeartha** [comment]
@danielroe Now it's starting properly, however playground is stuck in endless loading. I suspect that it has something to do with client ssr plugin:
```
Failed to load url /@fs/home/aleksa/.nvm/versions/node/v16.17.1/lib/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs?v=8bba95be (resolved id: /home/aleksa/.nvm/versions/node/v16.17.1/lib/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs?v=8bba95be) in virtual:nuxt:/home/aleksa/Desktop/Projects/nuxt-harlem-module/playground/.nuxt/plugins/client.mjs. Does the file exist?
```

**Comment by danielroe** [comment]
This seems to be working for me with devtools disabled - maybe it's not an issue with this module?

**Review by danielroe — APPROVED** [review]

**Comment by Lexpeartha** [comment]
Oops, seems I've forgot to disable devtools 😅 
You're right tho, without them it seems to be working fine, so I think we can merge this for now and maybe tackle this possible devtool issue in separate PR

**Pull request merged**
